### ISSUE TITLE
The Benchmark mobilenetv2 of Hailo-8L maybe error?

### ISSUE THREAD

**Issue by BUG1989** [hailo-ai/hailo_model_zoo#84]
https://github.com/hailo-ai/hailo_model_zoo/blob/master/docs/public_models/HAILO8L_Classification.rst
- Hailo-8L
  - mobilenetv1, 1867 fps
  - mobilenetv2, 280 fps ??

**Comment by nadaved1** [comment]
Hi @BUG1989 - interesting we will look into this

**Comment by omerwer** [comment]
Hi @BUG1989,
If you look at the relevant mobilenet_v2 line in the .rst of the Hailo8l you provided here, you'll see at the table you have a column of either batch-size 1 or 8. The benchmark results for batch size of 1 or batch size of 8 (hailortcli benchmark mobilenet_v2_1.0.hef --batch-size 8) are identical to those I get when running hailortcli run and to what is written in the .rst.
The reason is that the mobilenet_v2 model require more resources then the mobilenet_v1, which the hailo8l chip doesn't have enough of, so it's divided to multiple contexts, which hurts performance in comparison to single context, but as you can see can be improved by running it with larger batch size.

Regards,

**Comment by omerwer** [comment]
Hi @BUG1989 
By applying some compilation optimization, I was able to compile the model to a single context and reach 1658 FPS.
We will take this to the R&D to be available for the next release with the optimized compiled model.

Regards,

**Comment by BUG1989** [comment]
@omerwer @nadaved1  Thanks for your reply.
